"""Report generation node - creates final analysis report."""

from datetime import datetime
from framework.graph.node import Node, NodeContext


async def report_generation_node(context: NodeContext) -> dict:
    """
    Generate comprehensive contract evaluation report.
    
    Creates both markdown and JSON outputs.
    
    Input:
        - All data from previous nodes
        
    Output:
        - report_markdown: Formatted report
        - report_json: Structured data
        - report_path: Path where report was saved (if applicable)
    """
    input_data = context.input_data
    
    metadata = input_data.get("metadata", {})
    risk_assessment = input_data.get("risk_assessment", {})
    confidentiality = input_data.get("confidentiality", {})
    liability = input_data.get("liability", {})
    terms = input_data.get("terms", {})
    
    # Generate markdown report
    report_md = f"""# Contract Evaluation Report

## Contract Information
- **Contract ID**: {metadata.get('contract_id', 'N/A')}
- **Type**: {metadata.get('contract_type', 'Unknown')}
- **Jurisdiction**: {metadata.get('jurisdiction', 'Unknown')}
- **Parties**: {metadata.get('party_a', 'N/A')} and {metadata.get('party_b', 'N/A')}
- **Pages**: {metadata.get('page_count', 'N/A')}
- **Analysis Date**: {datetime.now().strftime('%Y-%m-%d %H:%M')}

## Executive Summary

**Overall Risk Score**: {risk_assessment.get('overall_risk_score', 0):.1f}/10

### Risk Breakdown
- Confidentiality Risk: {risk_assessment.get('confidentiality_risk', 0):.1f}/10
- Liability Risk: {risk_assessment.get('liability_risk', 0):.1f}/10
- Terms Risk: {risk_assessment.get('terms_risk', 0):.1f}/10

## Critical Issues
"""
    
    critical = risk_assessment.get('critical_issues', [])
    if critical:
        for issue in critical:
            report_md += f"- ⚠️ {issue}\n"
    else:
        report_md += "- None identified\n"
    
    report_md += "\n## Moderate Issues\n"
    moderate = risk_assessment.get('moderate_issues', [])
    if moderate:
        for issue in moderate[:5]:  # Top 5
            report_md += f"- {issue}\n"
    else:
        report_md += "- None identified\n"
    
    report_md += "\n## Detailed Findings\n\n### Confidentiality\n"
    report_md += f"- **Type**: {confidentiality.get('type', 'unclear')}\n"
    report_md += f"- **Scope**: {confidentiality.get('scope', 'Not specified')}\n"
    report_md += f"- **Duration**: {confidentiality.get('duration_months', 'Not specified')} months\n"
    report_md += f"- **Risk Level**: {confidentiality.get('risk_level', 'unknown')}\n"
    
    report_md += "\n### Liability & Indemnification\n"
    report_md += f"- **Liability Cap**: {'Yes' if liability.get('cap_present') else 'No'}\n"
    if liability.get('cap_amount'):
        report_md += f"- **Cap Amount**: {liability.get('cap_amount')}\n"
    report_md += f"- **Unlimited Liability**: {'Yes ⚠️' if liability.get('unlimited_liability') else 'No'}\n"
    report_md += f"- **Indemnification**: {liability.get('indemnification_type', 'unclear')}\n"
    report_md += f"- **Risk Level**: {liability.get('risk_level', 'unknown')}\n"
    
    report_md += "\n### Term & Obligations\n"
    report_md += f"- **Duration**: {terms.get('duration_months', 'Not specified')} months\n"
    report_md += f"- **Auto-Renewal**: {'Yes' if terms.get('auto_renewal') else 'No'}\n"
    if terms.get('notice_period_days'):
        report_md += f"- **Notice Period**: {terms.get('notice_period_days')} days\n"
    report_md += f"- **Termination for Convenience**: {'Yes' if terms.get('termination_for_convenience') else 'No'}\n"
    
    report_md += "\n## Recommendations\n"
    recommendations = risk_assessment.get('recommendations', [])
    if recommendations:
        for i, rec in enumerate(recommendations, 1):
            report_md += f"{i}. {rec}\n"
    else:
        report_md += "No specific recommendations at this time.\n"
    
    report_md += "\n## Next Steps\n"
    if risk_assessment.get('human_review_required'):
        report_md += f"- ⚠️ **Human legal review required**: {risk_assessment.get('human_review_reason')}\n"
        if input_data.get('review_approved'):
            report_md += "- ✅ Legal review completed\n"
            if input_data.get('reviewer_notes'):
                report_md += f"- **Reviewer Notes**: {input_data.get('reviewer_notes')}\n"
    else:
        report_md += "- Contract appears to have standard terms\n"
        report_md += "- Consider final review before signing\n"
    
    report_md += "\n---\n"
    report_md += "*This report was generated by an AI agent and should not be considered legal advice. "
    report_md += "All contracts should be reviewed by qualified legal counsel before signing.*\n"
    
    # Create JSON report
    report_json = {
        "contract_id": metadata.get('contract_id'),
        "analysis_timestamp": datetime.now().isoformat(),
        "metadata": metadata,
        "risk_assessment": risk_assessment,
        "findings": {
            "confidentiality": confidentiality,
            "liability": liability,
            "terms": terms,
        },
        "human_review": {
            "required": risk_assessment.get('human_review_required', False),
            "approved": input_data.get('review_approved'),
            "notes": input_data.get('reviewer_notes'),
        } if risk_assessment.get('human_review_required') else None,
    }
    
    return {
        "success": True,
        "report_markdown": report_md,
        "report_json": report_json,
        "contract_id": metadata.get('contract_id'),
    }


# Create the node instance
report_node = Node(
    id="report_generation",
    fn=report_generation_node,
    name="Report Generation",
    description="Generates comprehensive contract evaluation report",
)
